-- CREATE DATABASE FolloUp ;

USE FolloUp;

CREATE TABLE leads (
id INT(10) NOT NULL auto_increment PRIMARY KEY,
fullName  VARCHAR(150) NOT NULL,
address VARCHAR(400) NOT NULL,
email VARCHAR(150) NOT NULL,
phoneNumber VARCHAR(150) NOT NULL,
notes VARCHAR(1000) NOT NULL,
leadType VARCHAR(150) NOT NULL,
status VARCHAR(150) NOT NULL,
tracker VARCHAR(150) NOT NULL,
date VARCHAR(150) NOT NULL
);

